emm_inputs:
  base_elec_price: input/residential/BaseElecPrice.csv
  base_load: input/residential/BaseLoad.csv
  battery_efficiency: input/electricity/cem_inputs/BatteryEfficiency.csv
  cap_cost: input/electricity/cem_inputs/CapCost.csv
  cap_cost_initial: input/electricity/cem_inputs/CapCostInitial.csv
  cap_factor_vre: input/electricity/cem_inputs/CapFactorVRE.csv
  enduse_base_shares: input/residential/EnduseBaseShares.csv
  enduse_scalar: input/residential/EnduseScalar.csv
  enduse_shapes: input/residential/EnduseShapes.csv
  fom_cost: input/electricity/cem_inputs/FOMCost.csv
  h2_price: input/electricity/cem_inputs/H2Price.csv
  hours_to_buy: input/electricity/cem_inputs/HourstoBuy.csv
  hydro_cap_factor: input/electricity/cem_inputs/HydroCapFactor.csv
  learning_rate: input/electricity/cem_inputs/LearningRate.csv
  load_scalar: input/residential/LoadScalar.csv
  ramp_down_cost: input/electricity/cem_inputs/RampDownCost.csv
  ramp_rate: input/electricity/cem_inputs/RampRate.csv
  ramp_up_cost: input/electricity/cem_inputs/RampUpCost.csv
  reg_reserves_cost: input/electricity/cem_inputs/RegReservesCost.csv
  reserve_margin: input/electricity/cem_inputs/ReserveMargin.csv
  res_tech_upper_bound: input/electricity/cem_inputs/ResTechUpperBound.csv
  supply_curve: input/electricity/cem_inputs/SupplyCurve.csv
  supply_curve_learning: input/electricity/cem_inputs/SupplyCurveLearning.csv
  supply_price: input/electricity/cem_inputs/SupplyPrice.csv
  test_prices: input/residential/testPrices.csv
  tran_cost: input/electricity/cem_inputs/TranCost.csv
  tran_cost_int: input/electricity/cem_inputs/TranCostInt.csv
  tran_limit: input/electricity/cem_inputs/TranLimit.csv
  tran_limit_cap_int: input/electricity/cem_inputs/TranLimitCapInt.csv
  tran_limit_gen_int: input/electricity/cem_inputs/TranLimitGenInt.csv
