---
name: run-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 0" # Sundays at 8PM UTC

# What branch does this action run on?
# - workflow_dispatch: Whatever branch it was run against.
# - schedule: Always runs on main

env:
  TODAY: ""

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          cache: true

      - name: Run input pipeline
        run: pixi run snakemake --cores 2 emm_inputs
