---
name: run-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 0" # Sundays at 8PM UTC

# What branch does this action run on?
# - workflow_dispatch: Whatever branch it was run against.
# - schedule: Always runs on main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          cache: true

      # use command line config to make it harder to leak secrets
      - name: Run input pipeline
        run: |-
          pixi run snakemake \
            --cores 4 \
            --config environment=prod \
            --config r2.endpoint_url=${{ secrets.PROD_R2_ENDPOINT_URL }} \
            --config r2.access_key=${{ secrets.PROD_R2_ACCESS_KEY }} \
            --config r2.secret_key=${{ secrets.PROD_R2_SECRET_KEY }} \
            --config r2.bucket=cnems-inputs \
            emm_inputs
